version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: Weather
    ports:
      - "3307:3306"

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"

  weather-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather-app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/Weather
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - OPENWEATHERMAP_API_KEY=${OPENWEATHERMAP_API_KEY}
    ports:
      - "8081:8080"
    depends_on:
      - mysql
      - redis
